"""simplify food table

Revision ID: 63fc8b9eac16
Revises: 240fc8f2a529
Create Date: 2025-05-06 18:05:15.200785+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63fc8b9eac16'
down_revision: Union[str, None] = '240fc8f2a529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('carbon_footprint', sa.Float(), nullable=True))
    op.drop_column('foods', 'ethical_scores')
    op.drop_column('foods', 'nutrition')
    op.drop_column('foods', 'dietary_flags')
    op.drop_column('foods', 'environmental_scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('environmental_scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('foods', sa.Column('dietary_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('foods', sa.Column('nutrition', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('foods', sa.Column('ethical_scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('foods', 'carbon_footprint')
    # ### end Alembic commands ###
