"""update sources default value

Revision ID: f1edcb0dfe4a
Revises: 63fc8b9eac16
Create Date: 2025-05-06 18:08:13.330936+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1edcb0dfe4a'
down_revision: Union[str, None] = '63fc8b9eac16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foods', 'sources',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('foods', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('foods', 'sources',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
